source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MSThriftSerializer_Example', :exclusive => true do
  pod "MSThriftSerializer", :path => "../"
end

target 'MSThriftSerializer_Tests', :exclusive => true do
  pod "MSThriftSerializer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
