/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum Size {
  Size_SMALL = 1,
  Size_MEDIUM = 2,
  Size_LARGE = 3
};

@interface SimpleObject : NSObject <TBase, NSCoding> {
  NSString * __name;
  BOOL __isAwesome;
  int __size;

  BOOL __name_isset;
  BOOL __isAwesome_isset;
  BOOL __size_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=isAwesome, setter=setIsAwesome:) BOOL isAwesome;
@property (nonatomic, getter=size, setter=setSize:) int size;
#endif

- (id) init;
- (id) initWithName: (NSString *) name isAwesome: (BOOL) isAwesome size: (int) size;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (BOOL) isAwesome;
- (void) setIsAwesome: (BOOL) isAwesome;
#endif
- (BOOL) isAwesomeIsSet;

#if !__has_feature(objc_arc)
- (int) size;
- (void) setSize: (int) size;
#endif
- (BOOL) sizeIsSet;

@end

@interface SimpleObjectConstants : NSObject {
}
+ (NSString *) A_CONSTANT;
@end
